import {  Flight } from '../models/flight-models/flights';

export class FlightData{
    static flights:Flight[]=[
        {
            id:'60fc8922-091a-452c-a707-f344da5113be',
            company:'Indigo',
            flightCode:'6E-700',
            source:'BLR',
            destination:'KOL',
            departureTime:5.00,
            arrivalTime:7.00,
            totalCapacity:60,
            allocated:0,
            available:60,
            status:'Scheduled',
            airBusFamily:'A320'            
        },
        {
            id:'897538ca-7ce8-4ea9-aa2e-db91a798a277',
            company:'Indigo',
            flightCode:'6E-701',
            source:'BLR',
            destination:'KOL',
            departureTime:1.00,
            arrivalTime:4.00,
            totalCapacity:60,
            allocated:0,
            available:60,
            status:'Delayed' ,
            airBusFamily:'A320'            
        },
        {
            id:'29d73038-6cef-498e-ae3b-69e7fc87aefa',
            company:'Indigo',
            flightCode:'6E-702',
            source:'BLR',
            destination:'BOM',
            departureTime:4.00,
            arrivalTime:6.30,
            totalCapacity:60,
            allocated:0,
            available:60 ,
            status:'Scheduled' ,
            airBusFamily:'A320'            
        },
        {
            id:'499db1c5-18eb-436d-b869-b665dcafe2d4',
            company:'Indigo',
            flightCode:'6E-602',
            source:'BLR',
            destination:'BBS',
            departureTime:7.00,
            arrivalTime:9.00,
            totalCapacity:30,
            allocated:0,
            available:30     ,
            status:'Scheduled',
            airBusFamily:'A320'         
        },
        {
            id:'5db8d266-172e-4c16-830f-9714d3b15f10',
            company:'Indigo',
            flightCode:'6E-603',
            source:'BLR',
            destination:'DEL',
            departureTime:6.00,
            arrivalTime:8.30,
            totalCapacity:90,
            allocated:0,
            available:90    ,
            status:'Delayed'  ,
            airBusFamily:'A320'        
        },
        {
            id:'aba1b111-5e8e-4602-ae90-c8bfa5fcc598',
            company:'Indigo',
            flightCode:'6E-704',
            source:'BLR',
            destination:'HYD',
            departureTime:6.30,
            arrivalTime:7.30,
            totalCapacity:60,
            allocated:0,
            available:60  ,
            status:'Scheduled',
            airBusFamily:'A320'            
        },
        {
            id:'ae80e045-ba34-4616-a0b4-8a58f9621270',
            company:'Indigo',
            flightCode:'6E-705',
            source:'BLR',
            destination:'BOM',
            departureTime:15.00,
            arrivalTime:17.20,
            totalCapacity:60,
            allocated:0,
            available:60 ,
            status:'Scheduled'  ,
            airBusFamily:'A320'           
        },
        {
            id:'77c7f72c-c3e9-46e6-b9b5-71fe471bb19c',
            company:'Indigo',
            flightCode:'6E-706',
            source:'BLR',
            destination:'PAT',
            departureTime:13.00,
            arrivalTime:14.25,
            totalCapacity:90,
            allocated:0,
            available:60      ,
            status:'Cancelled'  ,
            airBusFamily:'A321'      
        },
        {
            id:'f44ea292-2877-40be-b0d3-595306367ba1',
            company:'Indigo',
            flightCode:'6E-707',
            source:'BLR',
            destination:'PAT',
            departureTime:12.00,
            arrivalTime:14.00,
            totalCapacity:60,
            allocated:0,
            available:60,
            status:'Scheduled' ,
            airBusFamily:'A320'      
        },
        {
            id:'e787b91e-26b0-4228-8898-86e6c5fdabfe',
            company:'Indigo',
            flightCode:'6E-807',
            source:'BLR',
            destination:'PAT',
            departureTime:19.10,
            arrivalTime:21.20,
            totalCapacity:60,
            allocated:0,
            available:60,
            status:'Scheduled',
            airBusFamily:'A320'              
        },
        {
            id:'34b417fc-d421-40c3-9a13-d9f8b2b3dcd1',
            company:'Indigo',
            flightCode:'6E-807',
            source:'BLR',
            destination:'PAT',
            departureTime:21.00,
            arrivalTime:23.10,
            totalCapacity:60,
            allocated:0,
            available:60 ,
            status:'Scheduled' ,
            airBusFamily:'A320'           
        },{
            id:'9260bb52-8ca6-4d23-9917-ab369c54a9b9',
            company:'Indigo',
            flightCode:'6E-808',
            source:'BLR',
            destination:'LKO',
            departureTime:20.00,
            arrivalTime:21.00,
            totalCapacity:60,
            allocated:0,
            available:60 ,
            status:'Scheduled',
            airBusFamily:'A320'             
        }
    ]
}